const fake_response = {
    "playlist_stats": {
        "total_playlist_count": 4,
        "total_created_playlist_count": 2,
        "total_saved_playlist_count": 2,
        "total_playlist_followers_count": 1973,
        "total_tracks_count": 208
    },
    "music_taste_stats": {
        "total_genres_general": 66,
        "total_genres_recently": 38,
        "top_general_music_genres": {
            "bass trap": 9,
            "edm": 9,
            "pop edm": 8,
            "traprun": 6,
            "electro house": 6,
            "indie poptimism": 5,
            "la pop": 4,
            "electropop": 4,
            "pop dance": 4,
            "tropical house": 4,
            "melodic dubstep": 4,
            "gaming edm": 3,
            "indie electropop": 3,
            "pop": 3,
            "brostep": 3,
            "electronic trap": 3,
            "future bass": 3,
            "nigerian pop": 2,
            "glitch hop": 2,
            "indietronica": 2,
            "dance pop": 2,
            "dark clubbing": 2,
            "breakbeat": 2,
            "filthstep": 2,
            "afro dancehall": 1,
            "afropop": 1,
            "azontobeats": 1,
            "alte": 1,
            "desi pop": 1,
            "speedrun": 1,
            "video game music": 1,
            "canadian hip hop": 1,
            "hip hop": 1,
            "melodic rap": 1,
            "pop rap": 1,
            "rap": 1,
            "toronto rap": 1,
            "trap": 1,
            "glitch": 1,
            "progressive electro house": 1,
            "melodic metalcore": 1,
            "metalcore": 1,
            "post-screamo": 1,
            "screamo": 1,
            "trancecore": 1,
            "german dance": 1,
            "scandipop": 1,
            "estonian pop": 1,
            "alt z": 1,
            "darksynth": 1,
            "nightrun": 1,
            "synthwave": 1,
            "pop rock": 1,
            "neon pop punk": 1,
            "pixie": 1,
            "pop punk": 1,
            "viral pop": 1,
            "metropopolis": 1,
            "post-teen pop": 1,
            "uk pop": 1,
            "vapor twitch": 1,
            "vapor soul": 1,
            "chillstep": 1,
            "experimental bass": 1,
            "classic dubstep": 1,
            "canadian electronic": 1
        },
        "top_recent_music_genres": {
            "synthwave": 15,
            "dark clubbing": 6,
            "spacewave": 4,
            "nightrun": 4,
            "pop edm": 3,
            "vapor twitch": 3,
            "darksynth": 3,
            "future rock": 2,
            "cyberpunk": 2,
            "vaporwave": 2,
            "electropop": 2,
            "future bass": 2,
            "chillstep": 2,
            "popwave": 2,
            "vgm remix": 2,
            "edm": 2,
            "electro house": 2,
            "filter house": 1,
            "phonk": 1,
            "wave": 1,
            "modular synth": 1,
            "lo-fi vgm": 1,
            "otacore": 1,
            "australian hip hop": 1,
            "speedrun": 1,
            "video game music": 1,
            "glitch": 1,
            "glitch hop": 1,
            "indietronica": 1,
            "indie poptimism": 1,
            "pop dance": 1,
            "progressive electro house": 1,
            "tropical house": 1,
            "melodic metalcore": 1,
            "metalcore": 1,
            "post-screamo": 1,
            "screamo": 1,
            "trancecore": 1
        },
        "top_recently_played": {
            "RISE": 10,
            "Diabolic": 8,
            "Night Train": 3,
            "Test Pilot": 1,
            "Ultimo": 1,
            "Metrocenter 84": 1,
            "Futureland": 1,
            "Aftershock": 1,
            "Nightride (Revisited)": 1,
            "The Navigator - Slowed Version": 1,
            "Spaceship Gurl - Dream Fiend Remix": 1,
            "9.30pm": 1,
            "Space Amplitude": 1,
            "Nostalgia": 1,
            "The Mansion": 1,
            "Visitors": 1,
            "Too Far Gone": 1,
            "Ascent": 1,
            "After Hours": 1,
            "Part Time God": 1,
            "Drift": 1,
            "Dangerous Dreams": 1,
            "Waves": 1,
            "Black To The Future": 1,
            "Neon Escapism - Edit": 1,
            "Slasher": 1,
            "Flight": 1,
            "Lost Woods": 1,
            "Enigma": 1,
            "Nuclear Sunday": 1,
            "Neo-Tokyo - Chromatique Remix": 1,
            "Astronaut In The Ocean": 1
        }
    },
    "total_artist_follow_count": 7,
    "artist_follow_average_popularity": 70,
    "photo_url": "https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=10152339579122040&height=300&width=300&ext=1618639798&hash=AeQzdD4hCQy7AB9C7nI",
    "display_name": "Robert Anizoba",
    "total_followers": 0,
    "platform_icon_url": "https://storage.googleapis.com/pr-newsroom-wp/1/2018/11/Spotify_Logo_RGB_White.png",
    "music_platform_name": "Spotify"
};

module.exports = fake_response;